### ISSUE TITLE
有关时间测量

### ISSUE THREAD

**Issue by little-squirrel-cute** [Gallium70/radix-sort-time-usage#1]
在本地测试 radix_sort.cc 可能受到 中断、异常、进程调度 等影响，导致时间测量结果不够稳定。可以尝试使用无干扰的测试系统（[评测鸭](https://duck.ac)）来进行测试。该测试系统提供了基数排序的题目（[测测你的排序](https://duck.ac/problem/1001)、[挑战-任务1](https://duck.ac/problem/wc2017b1)）和[排行榜](https://duck.ac/problem/1001/board)。

**Comment by Gallium70** [comment]
感谢建议，已添加测试结果和代码 https://duck.ac/submission/16009
